### ISSUE TITLE
Enhanced batch insert methods: tracking issue

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/jmt#56]
Per https://github.com/penumbra-zone/jmt/pull/55, deletion is successfully implemented for non-batch methods. However, these changes lead the JMT to use non-batch methods to commit versions. Previously, we were implicitly making use of the performance boost from batch operations because `put_value_set` was previously implemented in terms of `batch_put_value_sets`; in the version that's in `newmain` as of https://github.com/penumbra-zone/jmt/pull/55, it's been changed to be implemented in terms of (non-batch) `put_value_sets`.

In previous discussion, we thought this was not going to be a relevant problem, because we never commit more than one version at a time. However, this is actually a misunderstanding of what "batch" in these methods really means: the batch insertion methods don't actually save effort relative to the non-batch methods by batching across versions; they iterate over each version distinctly, just like the non-batch methods do; instead, they save time per version by only traversing the tree once per version (rather than once per key-value pair) to figure out all the insertions that need to be performed for that entire version. In the worst case, the key-value pairs within a version share little to no common prefixes, in which case the batch insertion methods save little time, but to whatever degree they share any common prefix, the batch insertion methods will save some number of lookups, and the bigger the number of operations per version, the more lookups saved.

Before diving into adapting `batch_put_value_sets` to perform deletions, we should:

- [x] https://github.com/penumbra-zone/jmt/issues/57

**Edit:** Having run the above benchmarks, I **do not** think it is worth it to upgrade the batch methods, because they **do not ever** affect the number of IO operations performed; they only save on hashmap lookups in the `TreeCache`, which is a very cheap operation comparatively to the cost of DB interaction.

- [x] https://github.com/penumbra-zone/jmt/issues/58

Finally, the JMT lacks a batch get operation, which would reap just the same efficiency gain as the batch insert does. When we implement range queries over key hash preimages, being able to batch-get the query (without having to execute it all at once, you could still stream it!) could speed things up just as batch insertion does. We should consider:

- [x] https://github.com/penumbra-zone/jmt/issues/59

**Comment by plaidfinch** [comment]
Here's the probability word problem which captures the *worst case* expected saved reads for batch insertion over ordinary insertion:

> Suppose I have a perfect N-ary tree of depth D, drawn on a big sheet of paper.
> 
> 1. I select K leaves uniformly, allowing duplicates.
> 2. For each leaf, I trace the path from the root to the leaf, placing a coin on each node of the tree as I go, all the way from the root to the leaf, inclusive of the root and the leaf. If another subsequent path also touches a node, I stack another coin on that node, until each node counts the total number of paths that pass through it to one of my selected leaves.
> 3. Finally, when I'm done iterating through every path to every leaf, i remove a single coin from every node that has any coins on it, and I throw all those coins away.
> 
> What is the expected total number of coins laid out on the tree now, as a function of N, D, and K?

**Comment by plaidfinch** [comment]
Closed after empirical evaluation and further analysis shows that the batch methods do not improve the number of IO operations necessary to perform an update; they merely improve the number of accesses to in-memory data structures, which are comparatively very cheap.
