### ISSUE TITLE
Tracking Issue: Combine with Sovereign-Labs/jmt

### ISSUE THREAD

**Issue by preston-evans98** [penumbra-zone/jmt#74]
## Background
Sovereign Labs and Penumbra are combining efforts to make one JMT to rule them all. This is a tracking issue for all of the changes from the [Sovereign Labs JMT](https://github.com/Sovereign-Labs/sovereign/tree/research/jmt) that we want to port over to this repo:

- [ ] Separate values from Leaf Nodes #73 
- [ ] Convert `Children` from a `HashMap` to an array 
- [ ] Make the JMT generic over hash function
- [ ] Feature gate metrics. See https://github.com/Sovereign-Labs/jellyfish-merkle-generic/blob/master/src/metrics/mod.rs
- [ ] Send all updates through the `batch_insert` API to share intermediate hashes
- [ ] Add optional parallelism with rayon

**Comment by hdevalence** [comment]
> Consider changing `TreeReader::get_value` to use `Key` instead of `KeyHash`

What if we made it take `K: Into<KeyHash>`?

**Comment by preston-evans98** [comment]
> What if we made it take `K: Into<KeyHash>`?

This is a good suggestion. I'll open a PR this afternoon. 

The underlying motivation for this item is to allow apps to efficiently retrieve a sequential keys using an iterator though, so just switching to `Into<KeyHash>` won't be sufficient. I'll open a separate issue where we can explore the tradeoffs.

**Comment by preston-evans98** [comment]
Hmm, on further thought I think this change will prevent `TreeReader` from being object safe

**Comment by zbuc** [comment]
In our weekly sprint planning, we pulled in all outstanding JMT issues and are wondering what the status of this one is. @preston-evans98 is there anything that needs to be done on our end?

**Comment by preston-evans98** [comment]
@zbuc Nothing immediate. I'll be trying to add `no_std` support this weekend, but the diff should be minimal and will just need review. I don't think we have any AIs here for the very short term
